name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This post has not been updated in 90 days. If it is no longer open or if you are no longer looking for work, this issue will automatically close in 10 days. If the position is still open or you are still looking for work, please remove the `stale` label or comment to keep the issue active.'
        stale-issue-label: 'stale'
        exempt-issue-label: 'admin-issue'
        days-before-stale: 90
        days-before-close: 10
